sudo: required
language: generic
services: docker

script:
  - script/release/package_release.sh dist
  - script/ci/setup.sh
  - docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind adnrv/texlive:full /repo/script/ci/travis-ci/build_all.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: luo4oHFf5+TZ/Nr74CN6/N73L5ndFQn/FtTnwo8Hj98x9Tr4zRCh9MYXzkR4+0KIx6T/X225BqhH71+zdMG9ZR84TTjuxPINKCxG1GLMGqCcMmsKpZb/IPGOi3Ku7BJOQmg+FM3Xi1STT6LpHIpEeK8mb5fkXOc8irEV1C82Z30j23n/fpUnkpQINBlKLiobe2AwzDsJmVxwffN0MuoqOIaeYW2m/hJ3ESDx3ocyYLR0GGpalV87TkIcmIG78XkBZy76pevd9tHy2XiUQXnoM1E2kyoQJJTWz26tCqa5+F8CfzZE7JruS2AdK8ZRu7X/xJ0hBVb0j+kw5QI2W7xxQZRaOgep6U3uaul4fCdkkwmZRwLh3WNYm6hX+UtpP49jY8WdOtsyOckp5pmhLWbRb8xheYcXyeoQC8n/b1eagtsetcpOyJDgsuSdaSljqrtBfC2wOiYuQwSv6SOWdLKqMCR2/8/YVrauGAffK3nlTkIXI3Odw7G7Lmjfwjf7l4mtZ37rPFTyJf8utJUWpPN6K5Cl3g9GZMvU2sogZknK/nlOw5rDHBkWlTtE3tcULhmXXudEj75vHIx/vNB2JNg1xofKvf8Z+oAjmWX/d7eohCW2y0ycaINIwRbKsLZ7sqMOip/naKRW53w5a2K2dGAC3JXkUOntzrTwUOaz02LQDoY=
  file_glob: true
  file: "dist/*"
  on:
    repo: TheNetAdmin/zjuthesis
    tags: true
  overwrite: true
